List alpha = [
    {"id": "#", "url": "?category=#"},
    {"id": "a", "url": "?category=a"},
    {"id": "b", "url": "?category=b"},
    {"id": "c", "url": "?category=c"},
    {"id": "d", "url": "?category=d"},
    {"id": "e", "url": "?category=e"},
    {"id": "f", "url": "?category=f"},
    {"id": "g", "url": "?category=g"},
    {"id": "h", "url": "?category=h"},
    {"id": "i", "url": "?category=i"},
    {"id": "j", "url": "?category=j"},
    {"id": "k", "url": "?category=k"},
    {"id": "l", "url": "?category=l"},
    {"id": "m", "url": "?category=m"},
    {"id": "n", "url": "?category=n"},
    {"id": "o", "url": "?category=o"},
    {"id": "p", "url": "?category=p"},
    {"id": "q", "url": "?category=q"},
    {"id": "r", "url": "?category=r"},
    {"id": "s", "url": "?category=s"},
    {"id": "t", "url": "?category=t"},
    {"id": "u", "url": "?category=u"},
    {"id": "v", "url": "?category=v"},
    {"id": "w", "url": "?category=w"},
    {"id": "x", "url": "?category=x"},
    {"id": "y", "url": "?category=y"},
    {"id": "z", "url": "?category=z"},
  ];

List genre = [
    {"title": "Action"},
    {"title": "Adventure"},
    {"title": "Comedy"},
    {"title": "Drama"},
    {"title": "Ecchi"},
    {"title": "Fantasy"},
    {"title": "Game"},
    {"title": "Horror"},
    {"title": "Harem"},
    {"title": "Magic"},
    {"title": "Martial Art"},
    {"title": "Romance"},
    {"title": "Sci-fi"},
    {"title": "School"},
    {"title": "Shounen"},
    {"title": "Seinen"},
    {"title": "Slice of Life"},
    {"title": "Supernatural"},
    {"title": "Super Power"},
];